OnlineShop/Models/EF/Footer.cs
namespace OnlineShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Footer")]
    public partial class Footer
    {
        [StringLength(50)]
        public string ID { get; set; }

        [Column(TypeName = "ntext")]
        public string Content { get; set; }

        public bool? Status { get; set; }
    }
}

OnlineShop/Models/EF/ProductCategory.cs
namespace OnlineShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("ProductCategory")]
    public partial class ProductCategory
    {
        public long ID { get; set; }

        [StringLength(250)]
        public string Name { get; set; }

        [StringLength(250)]
        public string MetaTitle { get; set; }

        public long? ParentID { get; set; }

        public int? DisplayOrder { get; set; }

        [StringLength(250)]
        public string SeoTitle { get; set; }

        public DateTime? CreatedDate { get; set; }

        [StringLength(50)]
        public string CreatedBy { get; set; }

        public DateTime? ModifiedDate { get; set; }

        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [StringLength(250)]
        public string MetaKeywords { get; set; }

        [StringLength(250)]
        public string MetaDescriptions { get; set; }

        public bool? Status { get; set; }

        public bool? ShowOnHome { get; set; }
    }
}

OnlineShop/Controllers/CartController.cs
using Microsoft.Ajax.Utilities;
using OnlineShop.Commons;
using OnlineShop.DAO;
using OnlineShop.Models;
using OnlineShop.Models.EF;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        private string cartSession = CommonConstants.CART_SESSION;
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[cartSession];
            var list = new List<CartItem>();
            if (cart != null)
            { 
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        public ActionResult AddItem(long productId, int quantity)
        {
            var product = new ProductDao().ViewDetail(productId);
            var cart = Session[cartSession];
            if(cart != null) 
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.ID == productId))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.ID == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //Tạo mới đối tượng Cart Item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
            }
            else
            {
                //Tạo mới đối tượng Cart Item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);
                //Gán vào Session
                Session[cartSession] = list;
            }
            return RedirectToAction("Index");
        }
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[cartSession];
            
            foreach(var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.ID == item.Product.ID);
                if(jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[cartSession] = sessionCart;
            return Json(new { status = true });
        }
        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[cartSession];
            sessionCart.RemoveAll(x=>x.Product.ID == id);
            Session[cartSession] = sessionCart;
            return Json(new { status = true });
        }
        public JsonResult DeleteAll()
        {
            Session[cartSession] = null;   
            return Json(new { status = true });
        }
        private int TotalQuantity() 
        {
            int total = 0;
            List<CartItem> list = Session[cartSession] as List<CartItem>;
            if (list != null)
            {
                total = list.Sum(x=>x.Quantity);
            }
            return total;
        }
        public ActionResult CartQuantity()
        {
            ViewBag.TotalQuantity = TotalQuantity();
            return PartialView();
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[cartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            else
            {
                return RedirectToAction("Index");
            }
            return View(list);
        }
        [HttpPost]
        public ActionResult Payment(string shipName, string phone, string address, string email)
        {
            var order = new Order();
            order.CreatedDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipPhone = phone;
            order.ShipName = shipName;
            order.ShipEmail = email;

            try
            {
                var id = new OrderDao().Insert(order);
                var cart = (List<CartItem>)Session[cartSession];
                var detailDao = new OrderDetailDao();
                decimal total = 0;
                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail();
                    orderDetail.ProductID = item.Product.ID;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Price;
                    orderDetail.Quantity = item.Quantity;
                    detailDao.Insert(orderDetail);

                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                }
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Content/client/assets/template/neworder.html"));

                content = content.Replace("{{CustomerName}}", shipName);
                content = content.Replace("{{Phone}}", phone);
                content = content.Replace("{{Email}}", email);
                content = content.Replace("{{Address}}", address);
                content = content.Replace("{{Total}}", total.ToString("N0"));
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new MailHelper().SendMail(email, "Đơn hàng mới từ OnlineShop", content);
                new MailHelper().SendMail(toEmail, "Đơn hàng mới từ OnlineShop", content);
            }
            catch (Exception ex)
            {
                //ghi log
                return Redirect("/loi-thanh-toan");
            }
            return Redirect("/hoan-thanh");
        }
        public ActionResult Success()
        {
            return View();
        }
        public ActionResult Fail()
        {
            return View();
        }
    }
}

OnlineShop/Controllers/UserController.cs
using BotDetect.Web.Mvc;
using Facebook;
using OnlineShop.Commons;
using OnlineShop.DAO;
using OnlineShop.Models;
using OnlineShop.Models.EF;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class UserController : Controller
    {
        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        // GET: User
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [CaptchaValidationActionFilter("CaptchaCode", "ExampleCaptcha", "Mã xác nhận không hợp lệ!")]
        public ActionResult Register(RegisterModel model)
        {
            if(ModelState.IsValid)
            {
                var dao = new UserDao();
                if(dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new User();
                    user.Username = model.UserName;
                    user.Password = EncryptorMD5.MD5Hash(model.Password);
                    user.Name = model.Name;
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    user.Address = model.Address;
                    user.CreatedDate = DateTime.Now;
                    user.Status = true;
                    var rs = dao.Insert(user);
                    if (rs > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công!";
                        //Reset model
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công!");
                    }
                }
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var rs = dao.Login(model.Username, EncryptorMD5.MD5Hash(model.Password));
                if (rs == 1)
                {
                    var user = dao.GetById(model.Username);
                    var userSession = new UserLogin();
                    userSession.UserName = user.Username;
                    userSession.UserID = user.ID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    return Redirect("/");
                }
                else if (rs == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại!");
                }
                else if (rs == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khóa!");
                }
                else if (rs == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không hợp lệ!");
                }
            }
            return View(model);
        }

        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;

                var user = new User();
                user.Email = email;
                user.Username = email;
                user.Status = true;
                user.Name = firstname + " " + middlename + " " + lastname;
                user.CreatedDate = DateTime.Now;
                var resultInsert = new UserDao().InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    var userSession = new UserLogin();
                    userSession.UserName = user.Username;
                    userSession.UserID = user.ID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                }
            }
            return Redirect("/");
        }

        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }
    }
}

OnlineShop/Views/Shared/Footer.cshtml
@model OnlineShop.Models.EF.Footer
@Html.Raw(Model.Content)

OnlineShop/Views/Shared/MainMenu.cshtml
@model List<OnlineShop.Models.EF.Menu>
@{
    var session = (OnlineShop.Commons.UserLogin)Session[OnlineShop.Commons.CommonConstants.USER_SESSION];
}
<!--
Navigation Bar Section
-->
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse">
                <ul class="nav">
                    @foreach (var item in Model)
                    {
                        <li><a href="@item.Link" target="@item.Target">@item.Text</a></li>
                    }
                </ul>
                <form action="#" class="navbar-search pull-left">
                    <input type="text" placeholder="Search" class="search-query span2">
                </form>
                @if (session == null)
                {
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#"><span class="icon-lock"></span> Đăng nhập <b class="caret"></b></a>
                            <div class="dropdown-menu">
                                @using (Html.BeginForm("Login", "User", FormMethod.Post, new { @class = "form-horizontal loginFrm" }))
                                {
                                    <div class="control-group">
                                        <input type="text" class="span2" id="inputEmail" name="Username" placeholder="Tài khoản">
                                    </div>
                                    <div class="control-group">
                                        <input type="password" class="span2" id="inputPassword" name="Password" placeholder="Mật khẩu">
                                    </div>
                                    <div class="control-group">
                                        <button type="submit" class="shopBtn btn-block">Đăng nhập</button>
                                    </div>
                                }
                            </div>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav pull-right">
                        <li>
                            @Html.ActionLink("Thoát", "Logout", "User")
                        </li>
                    </ul>
                }
                </div>
        </div>
    </div>
</div>

OnlineShop/Views/Shared/ProductCategory.cshtml
@model List<OnlineShop.Models.EF.ProductCategory>
<div class="well well-small">
    <h3>Danh mục sản phẩm</h3>
    <ul class="nav nav-list">
        @foreach (var item in Model.Where(x=>x.ParentID == null))
        {
            var child = Model.Where(x => x.ParentID == item.ID);
            var parentClass = child.Count() > 0 ? "class=dropdown-toggle data-toggle=dropdown" : "";
            <li class="dropdown">
                <a href="/san-pham/@item.MetaTitle-@item.ID" @parentClass>
                    <span class="icon-chevron-right"></span>@item.Name
                </a>
                @if (child.Count() > 0)
                {
                    <ul class="dropdown-menu">
                        @foreach (var childItem in child)
                        {
                            <li>
                                <a href="/san-pham/@childItem.MetaTitle-@childItem.ID">@childItem.Name</a>
                            </li>
                        }
                    </ul>
                }
            </li>
        }
    </ul>
</div>

OnlineShop/Views/Shared/TopMenu.cshtml
@model List<OnlineShop.Models.EF.Menu>
<!--
        Upper Header Section
    -->
@{ 
    var session = (OnlineShop.Commons.UserLogin)Session[OnlineShop.Commons.CommonConstants.USER_SESSION];
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="topNav">
        <div class="container">
            <div class="alignR">
                <div class="pull-left socialNw">
                    <a href="#"><span class="icon-twitter"></span></a>
                    <a href="#"><span class="icon-facebook"></span></a>
                    <a href="#"><span class="icon-youtube"></span></a>
                    <a href="#"><span class="icon-tumblr"></span></a>
                </div>
                @if (session == null)
                {
                    foreach (var item in Model)
                    {
                        <a href="@item.Link" target="@item.Target">@item.Text</a>
                    }
                }
                else
                {
                    <a href="#">Xin chào @session.UserName !</a>
                }
            </div>
        </div>
    </div>
</div>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Twitter Bootstrap shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap styles -->
    <link href="/Content/client/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- Customize styles -->
    <link href="/Content/client/style.css" rel="stylesheet" />
    <!-- font awesome styles -->
    <link href="/Content/client/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
        <link href="css/font-awesome-ie7.min.css" rel="stylesheet">
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Favicons -->
    <link rel="shortcut icon" href="/Content/client/assets/ico/favicon.ico">
</head>
<body>
    @Html.Action("TopMenu", "Home")
    <!--
    Lower Header Section
    -->
    <div class="container">
        <div id="gototop"> </div>
        <header id="header">
            <div class="row">
                <div class="span4">
                    <h1>
                        <a class="logo" href="/">
                            <span>Twitter Bootstrap ecommerce template</span>
                            <img src="/Content/client/assets/img/logo-bootstrap-shoping-cart.png" alt="bootstrap sexy shop">
                        </a>
                    </h1>
                </div>
                <div class="span4">                  
                </div>
                <div class="span4 alignR">
                    <p><br> <strong> Support (24/7) :  0800 1234 678 </strong><br><br></p>
                    @Html.Action("CartQuantity", "Cart")
                    <span class="btn btn-warning btn-mini">$</span>
                    <span class="btn btn-mini">&pound;</span>
                    <span class="btn btn-mini">&euro;</span>
                </div>
            </div>
        </header>
        @Html.Action("MainMenu", "Home")
        <!--
    Body Section
    -->
            @RenderSection("sidebar", required: false)
            @RenderBody()
        <!--
    Clients
    -->
        <section class="our_client">
            <hr class="soften" />
            <h4 class="title cntr"><span class="text">Manufactures</span></h4>
            <hr class="soften" />
            <div class="row">
                <div class="span2">
                    <a href="#"><img alt="" src="/Content/client/assets/img/1.png"></a>
                </div>
                <div class="span2">
                    <a href="#"><img alt="" src="/Content/client/assets/img/2.png"></a>
                </div>
                <div class="span2">
                    <a href="#"><img alt="" src="/Content/client/assets/img/3.png"></a>
                </div>
                <div class="span2">
                    <a href="#"><img alt="" src="/Content/client/assets/img/4.png"></a>
                </div>
                <div class="span2">
                    <a href="#"><img alt="" src="/Content/client/assets/img/5.png"></a>
                </div>
                <div class="span2">
                    <a href="#"><img alt="" src="/Content/client/assets/img/6.png"></a>
                </div>
            </div>
        </section>

        <!--
    Footer
    -->
        <footer class="footer">
            @Html.Action("Footer", "Home")
        </footer>
        <!-- Placed at the end of the document so the pages load faster -->
    </div><!-- /container -->

    <div class="copyright">
        <div class="container">
            <p class="pull-right">
                <a href="#"><img src="/Content/client/assets/img/maestro.png" alt="payment"></a>
                <a href="#"><img src="/Content/client/assets/img/mc.png" alt="payment"></a>
                <a href="#"><img src="/Content/client/assets/img/pp.png" alt="payment"></a>
                <a href="#"><img src="/Content/client/assets/img/visa.png" alt="payment"></a>
                <a href="#"><img src="/Content/client/assets/img/disc.png" alt="payment"></a>
            </p>
            <span>Copyright &copy; 2013<br> bootstrap ecommerce shopping template</span>
        </div>
    </div>
    <a href="#" class="gotop"><i class="icon-double-angle-up"></i></a>

    <script src="/Content/client/assets/js/jquery.js"></script>
    <script src="/Content/client/assets/js/bootstrap.min.js"></script>
    <script src="/Content/client/assets/js/jquery.easing-1.3.min.js"></script>
    <script src="/Content/client/assets/js/jquery.scrollTo-1.4.3.1-min.js"></script>
    <script src="/Content/client/assets/js/shop.js"></script>
    @RenderSection("jsFooter", required: false)
</body>
</html>